### ISSUE TITLE
Lanthanides and Actinides shifted by 1

### ISSUE THREAD

**Issue by mattbenscho** [remiberthoz/anki-periodic-table-memory-pegs#125]
Hey there! First of all, thanks for making the effort to publish the deck. Finally I can learn the periodic table!

I found that in the periodic table representation on the card there seems to be a off-by-one error. Lanthanum and Actinium are in the places of Cerium and Thorium, Cerium and Thorium are shifted one to the right, and Lutetium and Lawrencium are shown to be in the places of Lanthanum and Actinium. I didn't check the rest of the elements.

Is this a bug or just an alternative representation? I understand the position of the elements in the periodic table is sometimes not completely fixed.

**Comment by remiberthoz** [comment]
Hey! Thank you for raising this issue. I have been asked the question before, but not on GitHub: it will deserve a place in the FAQ when I create one.

I decided to display the table this way because IUPAC [has not decided](https://iupac.org/projects/project-details/?project_nr=2015-039-2-200) which elements constitute group 3 of the Periodic Table, and I personally like this presentation more.

But I am open to discuss this! My argument is that when representing the table in the 32-columns format, Lutetium and Lawrencium naturally fall under Scandium and Yttrium. Other representations of the 32-columns exists but they either *i)* do not respect the sequence of increasing atomic or *ii)* slice the block f in two parts. See [this resource](http://publications.iupac.org/images/ci/2012CI/3404/ud_fig4.jpg) for example: I am in favour of the top version.

Now given that the cards here represent the table in 18-columns, and that I use the IUPAC as a reference, I cannot argue against switching to a representation [like this one](https://iupac.org/wp-content/uploads/2018/12/IUPAC_Periodic_Table-01Dec18-1024x691.jpg) with 15 columns below the table.

**Comment by remiberthoz** [comment]
I'll close this issue because there is no more activity. Anyone feel free to reopen if you have questions or suggestions on this topic.
