### ISSUE TITLE
Suggestion: Positon --> Card

### ISSUE THREAD

**Issue by Green-Gatorade-Gottle** [remiberthoz/anki-periodic-table-memory-pegs#136]
Hi,

Great set! Thanks for maintaining it and I love the GitHub idea for contributions.

"The position of each element in the table gives important information about its structure, properties, and behavior in chemical reactions. Specifically, an element’s position in the periodic table helps you figure out its electron configuration, how the electrons are organized around the nucleus. "
-Khan Academy, _The periodic table, electron shells, and orbitals._

I think it would be helpful to have a version of the card where the Front is just the position of the element (and the Back is, of course, the entire card). There are many times when simply knowing where an element is on the table is useful. I know you have the different card types set up nicely and I think this change should be possible through an additional card type: Position --> Card. Let me know what you think. Thanks!

-GGG

**Comment by remiberthoz** [comment]
Hello,

I like this idea too. Learning positions of elements is a tougher challenge, though. I see two ways of implementing this:

- The most logical one would be to create a new *Card* for each element, such that the new Position for an element card appears in the user's reviews when Name, Symbol and Number of that element are learnt.
- An alternative would be to create a new *Model* for each element, allowing the Position note for *all* elements to load later in the learning process, when many or all elements Name, Symbol and Number are known already.

Do you have a preference?

In any case, since Anki allows users to disable specific *Card* types or *Models*, I think we can safely implement this in the deck and I will add a short step-by-step guide to remove Position cards from the deck, for users who would rather not have them.

**Comment by Green-Gatorade-Gottle** [comment]
I have a slight preference for the first idea. I believe that the majority of people just download the deck and never look back or question it; and because of this, I can see people complaining, being confused, or thinking it's an error that the Position Cards are at the end of the deck.

As you said, Anki lets you disable card types so that's always available for advanced users (if they want to). Just my 2 cents though. Ultimately, I think either version is fine for the position.

-GGG

P.S. The only scenario where I think a new Model would make sense is for Weight. Elemental weight is not as important to memorize (though, it is useful) but by the time you get tested and need to know about the weights, you're doing tests where the periodic table is given to you. So for Weight, I think the justifications for a new model would be a lot stronger. I'm not advocating for adding weight. Just an example.

**Comment by remiberthoz** [comment]
Thanks, you have a point.

I won't do it today, but I would like to finish this within the week.

**Comment by remiberthoz** [comment]
Surely yes, but this is the card type you had in mind, right? (available from commit [e57a567](https://github.com/remiberthoz/anki-periodic-table-memory-pegs/commit/e57a56795af1b9f30df4232bad9f6c752662c2c0))

In addition to the highlighted position in the table, what would you think of indicating the element's period and group (row and column) on both sides of the card? 

<div align="center">

![Combined Stacks](https://user-images.githubusercontent.com/1943662/182626427-da578cc0-a18a-4c52-b849-66dba2df31d3.jpg)
</div>

----

The only problem I see is that if you make a mistake, you cannot estimate how far you were from the truth. Let's say I see this card and I guess "Uranium", I cannot evaluate my guess as compared to someone who guesses "Phosphorus". It would be good to show in the table on the back side, symbols for all elements. This is however a bit heavy and unreadable especially on smartphone screens where text would be tiny.

**Comment by Green-Gatorade-Gottle** [comment]
That is what I had in mind.

Indicating the element's period and group (row and column) on both sides of the card sounds like a good idea to me.

As for your last bit, I think it's okay not to reveal all the symbols for the reasons you said (too heavy and unreadable). But I also don't see this becoming a huge problem. Anki is made for memorizing and as long as you're getting feedback on whether you were, right, wrong or close, I think you still learn plenty from the card. I wouldn't worry about this problem too much—ultimately, we are limited to what we can do.

One question, is the square shape of the cards something that must stay? A longer card could help solve the problem of readability somewhat (not to show all elements, but to add periods and groups). The small screen problem is only a problem with smartphones, and most of them are 16:9 aspect ratio, and most people hold their phone in this orientation, so why not make the card in this shape?

e.i.
![image](https://user-images.githubusercontent.com/110424809/182655580-b7fac790-02fd-4b61-a428-45f8e0177a55.png)

**Comment by remiberthoz** [comment]
Thanks for your feedback.

That card style would work, there is no reason to make square cards (I don't know why I made them square in the first place). Where would we then place the group and period information? Maybe cleanly indicated near the element's name, or as row and column headers for the table like so:

<div align="center">

![Screenshot from 2022-08-03 22-36-10](https://user-images.githubusercontent.com/1943662/182706848-3c11647c-6513-4a46-941b-3bff23fb5106.png)
</div>

**Comment by Green-Gatorade-Gottle** [comment]
Yeah, I like having the numbers like in your example. I do wonder if there is a better font for small screens (actual question, the one you have might very well be the best already).

Similar to the shape discussion above: have you considered removing margins to allow more space? I do like the idea of the card having a fixed ratio in size so that the text doesn't stretch for widescreen monitors, etc.... but if there was a way to remove the margins you could get more screen space (or reduce margins).

Also, I think that creating more contrast between background and text could also aid in readability. [Vox](https://www.vox.com/), for example, uses pure white (#FFFFFF) with font on Dark Grey (#4B4D4C). [NYTimes](https://www.nytimes.com/) also uses white with a really dark (but not black) grey. My point is: while I like the off-black setup, and I do believe it helps with eyestrain; the cards might benefit from added contrast by making the background on the bottom portion full white.

**Comment by remiberthoz** [comment]
Yes, the original design for the deck was based on Google's *Material Design* (https://material.io/design), which as evolved as well.

**Comment by remiberthoz** [comment]
> have you considered removing margins to allow more space?

Yes, sadly I have no clue of how to make this work for all devices. Computers (full screen or windowed), tablets, smartphone, ... I have only basic knowledge of CSS/HTML and I do not know how Anki implements the web views.

There is a great CSS/HTML periodic table here: https://codepen.io/nemophrost/pen/nZZydJ, under MIT License meaning we could use it. I tried tinkering but I always end up with strange results if I do not impose a fixed-size card.

**Comment by remiberthoz** [comment]
I pushed commit [82241c4](https://github.com/remiberthoz/anki-periodic-table-memory-pegs/commit/82241c477811914033a40babd48c736309a8cfde) a moment ago, implementing the style displayed [four comments above](https://github.com/remiberthoz/anki-periodic-table-memory-pegs/issues/136#issuecomment-1204457802). I haven't updated the layout as suggested by @Green-Gatorade-Gottle [five comments above](https://github.com/remiberthoz/anki-periodic-table-memory-pegs/issues/136#issuecomment-1204154049), but I think it would be cool.

Since we addressed the original intent of this issue, I'm going to close it. When I upload the changes to Ankiweb, I will also open a new issue here on Github regarding a pending redesign of the deck.

If you want to add, comment, or raise a new issue regarding the Position cards, feel free to re-open this issue or create a new one.
